### PR TITLE
Added Spanish Language files

### PR DESCRIPTION
**Pull request by sonicalabs**
Just translated english language files to spanish

### CODE REVIEW

**Comment by sebastienheyd** [comment]
Hello,

Thank you for the great job ! ;)

I will see to add it asap.

**Comment by sonicalabs** [comment]
My pleasure !!
by the way, seems Arcanelog doesn't work with laravel 5.6 or I can't get it to work with latest boilerplate version. Have you noticed something like this?

I'm going to translate to Catalan and add fontawesome 5 in the next days, glad if u pull that too if you like.

Something I can help u, just ask !!

**Comment by sebastienheyd** [comment]
For ArcaneLog I noticed that Laravel has changed the default value in the configuration.

To reactivate ArcaneLog, just edit the config/logging.php file and change the channels/stack/channels value from single to daily and it will work again.

I will see to overload this default value when installing boilerplate.

Good idea to add FontAwesome 5, I just added this to my todo list: https://github.com/sebastienheyd/boilerplate/projects/1

**Comment by sebastienheyd** [comment]
I can't get the pull request back as it is. Ideally it would have been necessary to separate the language files from the javascript to integrate it properly. I had to do it to add the documentation but also the files of the Spanish locales from Laravel.

So I have used the localization files for the moment, I would continue with datetime, but probably not parsley yet that I find quite heavy and not useful for the moment.

For datetime and parsley it misses moreover the modifications in webpack and package json to have a correct pull request.

I made the correction to enable daily logs by default so that ArcaneLog works again.

I close the pull request and save it for later.

**Pull request closed without merging**
